### ISSUE TITLE
What else is needed? 

### ISSUE THREAD

**Issue by rweitzman** [vse-volod/gatsby-starter-porto#2]
<img width="692" alt="Screen Shot 2022-01-15 at 4 16 56 PM" src="https://user-images.githubusercontent.com/78377068/149642287-2c09a69f-5c93-4c55-93ce-15730a206f66.png">

**Comment by vse-volod** [comment]
Looks like you didn't made a fork of actual theme repository when you was redirected from gumroad. But that's okay, I sent you invite to the new repo with new version of theme(updated a few days ago). 
Accept invite and fork that repo, then again install theme using command above.
Let me know if you have any other questions

**Comment by vse-volod** [comment]
Issue resolved
